### PR TITLE
Add method for unread messages count

### PR DESCRIPTION
**Pull request by adnedelcu**

### CODE REVIEW

**Comment by adnedelcu** [comment]
What is the status on this?

**Comment by mukeshthawani** [comment]
@adnedelcu Thanks for the PR. Our team will review it soon.

**Comment by reytum** [comment]
@adnedelcu  The code was given to you for your projects's use case. Please note that we have a plugin which can have multiple use cases and thus we would like to keep only the generic codebase in it. Unfortunately we cannot merge this as it will effect the generic behaviour of the plugin.

**Comment by adnedelcu** [comment]
So if we want to release our application we have to either remove this feature or implement our own Flutter plugin for Kommunicate that has this feature?

**Comment by reytum** [comment]
@adnedelcu You don't need to create your own flutter plugin. After installing the kommunicate plugin in your application, you can just add the method in the same plugin and it should work. You can release your app with that.

**Comment by adnedelcu** [comment]
But this means that we can't use a build system to do release the application and every developer needs to do this "hack" everytime you release a new version yourself.

**Comment by reytum** [comment]
@adnedelcu You can write the steps in a document. You don't need to do it every time. Just after you remove kommunicate plugin and add it again, thats when you need to add the changes. If you do not remove the plugin, the changes will be there. Also the changes you made are only for android. To make the plugin stable we need to add the iOS related code as well. We will check if this can be added. But still the notification related changes need to be added as specific function.

**Comment by adnedelcu** [comment]
The changes I did were not just for Android, they are also for iOS (there is a swift file that is changed also). I'm talking about the unread count functionality.
I realise that the code for Android also contains the notification functionality. I will remove it as indeed it might affect the stability of the integration.

**Comment by adnedelcu** [comment]
> You can write the steps in a document. You don't need to do it every time. Just after you remove kommunicate plugin and add it again, thats when you need to add the changes. If you do not remove the plugin, the changes will be there.

What about the build system? The build system will install the plugin everytime it builds. This would mean that we would have to create a step in the build system to add the code while building.

**Comment by Samir1810** [comment]
@adnedelcu Hi Daniel. Ashish will update you soon.

**Review by reytum — APPROVED** [review]

**Comment by reytum** [comment]
@adnedelcu  Released with version 1.1.4. Thanks for the contributions to this Plugin.

**Pull request merged**
